#load @"include.system.collections.fsx" 
#load @"include.system.collections.concurrent.fsx" 
#load @"include.system.linq.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.runtime.handles.fsx" 
#load @"include.system.runtime.interopservices.fsx" 
#load @"include.system.security.cryptography.primitives.fsx" 
#load @"include.system.text.encoding.fsx" 
#r "System" 
#r "../../../packages/System.Security.Cryptography.Encoding/lib/net46/System.Security.Cryptography.Encoding.dll" 
printfn "system.security.cryptography.encoding Loaded" 