#load @"include.system.globalization.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#r "System.Numerics" 
printfn "system.runtime.numerics Loaded" 