#load @"include.system.collections.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.diagnostics.tracing.fsx" 
#load @"include.system.globalization.fsx" 
#load @"include.system.io.fsx" 
#load @"include.system.net.http.fsx" 
#load @"include.system.net.primitives.fsx" 
#load @"include.system.net.webheadercollection.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.threading.fsx" 
#load @"include.system.threading.tasks.fsx" 
#r "System" 
printfn "system.net.requests Loaded" 