#load @"include.system.io.fsx" 
#load @"include.system.reflection.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.runtime.handles.fsx" 
#load @"include.system.runtime.interopservices.fsx" 
#load @"include.system.security.cryptography.algorithms.fsx" 
#load @"include.system.security.cryptography.encoding.fsx" 
#load @"include.system.security.cryptography.primitives.fsx" 
#load @"include.system.text.encoding.fsx" 
#load @"include.system.threading.fsx" 
#r "../../../packages/System.Security.Cryptography.Csp/lib/net46/System.Security.Cryptography.Csp.dll" 
printfn "system.security.cryptography.csp Loaded" 