#load @"include.system.io.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.runtime.extensions.fsx" 
#load @"include.system.runtime.handles.fsx" 
#load @"include.system.runtime.interopservices.fsx" 
#load @"include.system.security.cryptography.algorithms.fsx" 
#load @"include.system.security.cryptography.encoding.fsx" 
#load @"include.system.security.cryptography.primitives.fsx" 
#load @"include.system.text.encoding.fsx" 
#r "System.Core" 
#r "../../../packages/System.Security.Cryptography.Cng/lib/net46/System.Security.Cryptography.Cng.dll" 
printfn "system.security.cryptography.cng Loaded" 