#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.globalization.fsx" 
#load @"include.system.io.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#load @"include.system.threading.fsx" 
#load @"include.system.threading.tasks.fsx" 
#r "../../../packages/System.Security.Cryptography.Primitives/lib/net46/System.Security.Cryptography.Primitives.dll" 
printfn "system.security.cryptography.primitives Loaded" 