#load @"include.system.collections.fsx" 
#load @"include.system.diagnostics.debug.fsx" 
#load @"include.system.linq.fsx" 
#load @"include.system.linq.expressions.fsx" 
#load @"include.system.reflection.fsx" 
#load @"include.system.reflection.extensions.fsx" 
#load @"include.system.resources.resourcemanager.fsx" 
#load @"include.system.runtime.fsx" 
#r "System.Core" 
printfn "system.linq.queryable Loaded" 